### ISSUE TITLE
Player statistics with country of origin

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRAWeb#197] opened 2015-02-10 10:29 UTC
It would be nice to have statistics about where openra players are coming from at http://www.openra.net/players/.

**Comment by deniz1a** [comment] 2015-02-10 10:33
And the page doesn't say which time zone is used for the hourly graph. Is it GMT?

**Comment by deniz1a** [comment] 2015-02-10 10:36
And wouldn't it be better if the hover text over the graphs had both playing and waiting numbers shown at the same time?

**Comment by ihptru** [comment] 2015-02-10 12:04
yes it's UTC

**Comment by Mailaender** [comment] 2015-03-15 17:50
There is http://res0l.net/src/LiveORA/map.html but it seems pretty broken and unpolished.

**Comment by pchote** [comment] 2017-10-13 19:10
Closing as reverse duplicate of #322.

**Closed by pchote** 2017-10-13 19:10 UTC
Labels: enhancement
